[package]
name = "cargo-uf2"
version = "0.1.0"
authors = ["Jacob <jacobrosenthal@gmail.com>"]
edition = "2018"


[dependencies]
structopt = "0.3.2"
cargo-project = "0.2.2"
colored = "1.8.0"
uf2 = {path ="../uf2-rs"}
hidapi = "0.5.2"
crc = "1.9.0"

